gcc:
  image: fedora:28
  stage: build
  script:
    - dnf install -y meson gcc-c++
    - meson build
    - ninja -C build
    - ./build/example
    - ninja -C build test install

clang:
  image: fedora:28
  stage: build
  script:
    - dnf install -y meson clang
    - CC=clang CXX=clang++ meson build
    - ninja -C build test
    - ./build/example

mingw:
  image: fedora:28
  stage: build
  script:
    - dnf install -y gcc-c++ meson mingw64-gcc-c++ wine-core
    - meson build --cross-file mingw.ini
    - WINEPATH=/usr/x86_64-w64-mingw32/sys-root/mingw/bin ninja -C build test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
